---
- name: Test Incus CLI
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  vars:
    project: "Default"
    remote: "incusos1"
    image: "images:debian/13"
    container: "c3"

  tasks:
    - name: List containers
      incus_cli:
        command: "incus list {{ remote }}:"
      register: result
      changed_when: false
    - name: Afficher le résultat de la commande
      debug:
        var: result.stdout

    - name: Déployer un conteneur sur un serveur distant
      incus_cli:
        template: ../templates/create_container.j2
        debug: false
        vars:
          image: "{{ image }}"
          container: "{{ container }}"
      when: container not in result.stdout
