---
- name: Test Incus
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Test Incus
      shell: |
        incus profile list
        incus list
        incus network list
        incus storage list
        incus storage volume list local
      register: result
      changed_when: false

    - name: Show Result
      debug:
        var: result
